#pragma once

enum TEXTYPE { TEX_SINGLE, TEX_MULTI, TEX_END };

enum SCENEID { SC_LOGO, SC_STAGE, SC_ENDING, SC_END };

enum OBJID { OBJ_BACK, OBJ_BUILDING, OBJ_PLAYER, OBJ_ENEMY, OBJ_ACTIVE, OBJ_UI, OBJ_ITEM, OBJ_MOUSE, OBJ_EFFECT, OBJ_END };

enum RENDERID { RENDER_BACK, RENDER_BOAT, RENDER_OBJ, RENDER_EFFECT, RENDER_UI, END };

enum MOVEDIR { MOVE_IDLE, MOVE_U, MOVE_RU, MOVE_R, MOVE_RB, MOVE_B, MOVE_LB, MOVE_L, MOVE_LU };

enum STATEID { STATE_IDLE, STATE_WALK, STATE_ATTECT, STATE_END };